services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: evotes_dev
      POSTGRES_PASSWORD: evotes_dev_pwd
      POSTGRES_DB: evotes_dev_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/evotes
    command: sh -c "python wait_for_db.py && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=evotes_dev_db
      - DB_USER=evotes_dev
      - DB_PASSWORD=evotes_dev_pwd
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data:
