services:
  - type: web
    name: evotes-web
    env: docker
    plan: free
    repo: https://github.com/johnkenzzy/evotes
    branch: main
    dockerfilePath: backend/Dockerfile
    startCommand: sh -c "python wait_for_db.py && python manage.py runserver 0.0.0.0:8000"
    envVars:
      - key: DB_NAME
        value: evotes_db
      - key: DB_USER
        value: evotes_dev
      - key: DB_PASSWORD

      - key: DB_HOST

      - key: DB_PORT
        value: "5432"
