# Generated by Django 4.2.20 on 2025-04-10 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            'organizations', 
            '0002_alter_organization_address_alter_organization_logo_and_more'
            ),
        ('ballots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='organization',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE,
                to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='option',
            name='organization',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE,
                to='organizations.organization'),
        ),
    ]
