# Generated by Django 4.2.20 on 2025-04-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ballots', '0002_ballot_organization_option_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballot',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='option',
            name='organization',
        ),
    ]
