# Generated by Django 4.2.20 on 2025-04-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ballots', '0003_remove_ballot_organization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ballot',
            old_name='end_date',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='ballot',
            old_name='start_date',
            new_name='start_time',
        ),
    ]
