# Generated by Django 4.2.20 on 2025-04-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballots', '0004_rename_end_date_ballot_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='photo',
            field=models.ImageField(blank=True, default='candidate_images/default.jpg', null=True, upload_to='candidate_images/'),
        ),
    ]
