# Generated by Django 4.2.20 on 2025-04-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballots', '0005_alter_option_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
