# Generated by Django 4.2.20 on 2025-04-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='name',
        ),
        migrations.AlterField(
            model_name='election',
            name='title',
            field=models.CharField(default='New Election', max_length=255),
        ),
    ]
