# Generated by Django 4.2.20 on 2025-04-21 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_remove_election_name_alter_election_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='organisation',
            new_name='organization',
        ),
    ]
