# Generated by Django 4.2.20 on 2025-04-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_rename_organisation_election_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
