# Generated by Django 4.2.20 on 2025-04-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organizationadmin_is_super_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, default='organization_logo/default.jpg', null=True, upload_to='organization_logos/'),
        ),
    ]
