# Generated by Django 4.2.20 on 2025-04-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organization_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='password',
        ),
        migrations.RemoveField(
            model_name='organizationadmin',
            name='is_super_admin',
        ),
        migrations.AddField(
            model_name='organizationadmin',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin')], default='admin', max_length=30),
        ),
    ]
