# Generated by Django 4.2.20 on 2025-04-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0005_remove_organization_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationadmin',
            options={},
        ),
        migrations.AddField(
            model_name='organizationadmin',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='organization_admins', to='auth.group'),
        ),
        migrations.AddField(
            model_name='organizationadmin',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='organizationadmin',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='organizationadmin',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='organization_admins_permissions', to='auth.permission'),
        ),
    ]
