# Generated by Django 4.2.20 on 2025-04-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0006_alter_organizationadmin_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationadmin',
            name='groups',
            field=models.ManyToManyField(related_name='organization_admins', to='auth.group'),
        ),
    ]
