# Generated by Django 4.2.20 on 2025-04-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0007_alter_organizationadmin_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationadmin',
            name='groups',
            field=models.ManyToManyField(null=True, related_name='organization_admins', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='organizationadmin',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, null=True, related_name='organization_admins_permissions', to='auth.permission'),
        ),
    ]
