# Generated by Django 4.2.20 on 2025-04-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0002_vote_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='organization',
        ),
    ]
