# Generated by Django 4.2.20 on 2025-04-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0003_remove_vote_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='has_voted',
            new_name='is_verified',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='is_accredited',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='voter_id',
        ),
        migrations.AddField(
            model_name='voter',
            name='code_expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='sign_in_code',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
