# Generated by Django 4.2.20 on 2025-04-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0004_rename_has_voted_voter_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='role',
            field=models.CharField(default='voter', max_length=30),
        ),
    ]
