# Generated by Django 4.2.20 on 2025-04-22 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0005_voter_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='organisation',
            new_name='organization',
        ),
    ]
