# Generated by Django 4.2.20 on 2025-04-22 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0007_alter_voter_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='code_expires_at',
            new_name='expires_at',
        ),
    ]
